;; ultramark.wat — hand-written WebAssembly port of the ultramark streaming
;; markdown core (strict subset). Mirrors src/index.ts: a line-fed block state
;; machine + a single-pass inline pipeline with a stash side-table.
;;
;; Memory map (bytes; single linear memory, 1024 pages = 64 MiB):
;;   0x0000000  literal blob (string constants) + align words
;;   0x0100000  INBUF     host input staging (<= ~8 MiB per push)
;;   0x1000000  STABLE    stable output arena (push/end append here)
;;   0x2000000  SCRATCH   peek output arena (tentative render)
;;   0x2400000  W0/W1     inline ping-pong buffers
;;   0x2C00000  JOIN      line-join / table-align scratch / list index
;;   0x2E00000  STASHB    inline stash bytes
;;   0x3000000  STASHT    inline stash table (i32 off,len pairs)
;;   0x3100000  ARENA     block line records (bump; stack discipline)
;;   0x3700000  BUFREG    top-level partial-line buffer
;;   0x3B00000  TEMPP     peek clone parser struct
;;   0x3B40000  STATE     parser struct bump arena
;;
;; Parser struct (320 bytes): OPEN(0) INFO_P(4) INFO_L(8) FCH(12) FCNT(16)
;;   LSTART(20) LCNT(24) ; INFO buffer inline at +64 (256 bytes).
(module
  (memory (export "memory") 1024)

  ;; ---- region bases (immutable) ----
  (global $INBUF   i32 (i32.const 0x0100000))
  (global $STABLE  i32 (i32.const 0x1000000))
  (global $SCRATCH i32 (i32.const 0x2000000))
  (global $W0      i32 (i32.const 0x2400000))
  (global $W1      i32 (i32.const 0x2800000))
  (global $JOIN    i32 (i32.const 0x2C00000))
  (global $STASHB0 i32 (i32.const 0x2E00000))
  (global $STASHT  i32 (i32.const 0x3000000))
  (global $ARENA0  i32 (i32.const 0x3100000))
  (global $BUFREG  i32 (i32.const 0x3700000))
  (global $TEMPP   i32 (i32.const 0x3B00000))
  (global $STATE0  i32 (i32.const 0x3B40000))

  ;; ---- mutable state ----
  (global $op    (mut i32) (i32.const 0)) ;; current output write cursor
  (global $arena (mut i32) (i32.const 0)) ;; line-record bump
  (global $state (mut i32) (i32.const 0)) ;; parser struct bump
  (global $buflen (mut i32) (i32.const 0));; top-level partial buffer length
  (global $stc   (mut i32) (i32.const 0)) ;; stash count
  (global $stb   (mut i32) (i32.const 0)) ;; stash bytes bump

  ;; matcher scratch return slots
  (global $r0 (mut i32) (i32.const 0))
  (global $r1 (mut i32) (i32.const 0))
  (global $r2 (mut i32) (i32.const 0))
  (global $r3 (mut i32) (i32.const 0))
  (global $rp (mut i32) (i32.const 0))
  (global $rl (mut i32) (i32.const 0))

  ;; ---- literal blob (see wasm/build note; offsets are stable) ----
  (data (i32.const 256) "<p></p>\0a<h></h>\0a<hr>\0a<pre><code class=\22language-\22></code></pre>\0a<blockquote>\0a</blockquote>\0a<ul<ol start=\22>\0a<li></li>\0a</ul>\0a</ol>\0a<table>\0a<thead>\0a<tr></tr>\0a</thead>\0a<tbody>\0a</tbody>\0a</table>\0a<tr></tr>\0a<th</th><td</td> align=\22\22<input type=\22checkbox\22 disabled checked> <code></code><a href=\22\22></a><img src=\22\22 alt=\22\22><strong></strong><em></em><del></del>&amp;&lt;&gt;&quot;#javascriptvbscripthttp")
  (data (i32.const 648) "leftrightcenter")

  ;; literal offset/len constants (from generator)
  (global $P_O i32 (i32.const 256)) (global $P_OL i32 (i32.const 3))
  (global $P_C i32 (i32.const 259)) (global $P_CL i32 (i32.const 5))
  (global $H_O i32 (i32.const 264)) (global $H_OL i32 (i32.const 2))
  (global $H_MID i32 (i32.const 266)) (global $H_MIDL i32 (i32.const 1))
  (global $H_C i32 (i32.const 267)) (global $H_CL i32 (i32.const 3))
  (global $H_END i32 (i32.const 270)) (global $H_ENDL i32 (i32.const 2))
  (global $HR i32 (i32.const 272)) (global $HRL i32 (i32.const 5))
  (global $PRE_O i32 (i32.const 277)) (global $PRE_OL i32 (i32.const 10))
  (global $LANG i32 (i32.const 287)) (global $LANGL i32 (i32.const 17))
  (global $TAG_C i32 (i32.const 304)) (global $TAG_CL i32 (i32.const 2))
  (global $PRE_C i32 (i32.const 306)) (global $PRE_CL i32 (i32.const 14))
  (global $BQ_O i32 (i32.const 320)) (global $BQ_OL i32 (i32.const 13))
  (global $BQ_C i32 (i32.const 333)) (global $BQ_CL i32 (i32.const 14))
  (global $UL_O i32 (i32.const 347)) (global $UL_OL i32 (i32.const 3))
  (global $OL_O i32 (i32.const 350)) (global $OL_OL i32 (i32.const 3))
  (global $START i32 (i32.const 353)) (global $STARTL i32 (i32.const 8))
  (global $GT_NL i32 (i32.const 361)) (global $GT_NLL i32 (i32.const 2))
  (global $LI_O i32 (i32.const 363)) (global $LI_OL i32 (i32.const 4))
  (global $LI_C i32 (i32.const 367)) (global $LI_CL i32 (i32.const 6))
  (global $UL_C i32 (i32.const 373)) (global $UL_CL i32 (i32.const 6))
  (global $OL_C i32 (i32.const 379)) (global $OL_CL i32 (i32.const 6))
  (global $TBL_O i32 (i32.const 385)) (global $TBL_OL i32 (i32.const 20))
  (global $THEAD_C i32 (i32.const 405)) (global $THEAD_CL i32 (i32.const 23))
  (global $TBL_C i32 (i32.const 428)) (global $TBL_CL i32 (i32.const 18))
  (global $TR_O i32 (i32.const 446)) (global $TR_OL i32 (i32.const 4))
  (global $TR_C i32 (i32.const 450)) (global $TR_CL i32 (i32.const 6))
  (global $TH_O i32 (i32.const 456)) (global $TH_OL i32 (i32.const 3))
  (global $TH_C i32 (i32.const 459)) (global $TH_CL i32 (i32.const 5))
  (global $TD_O i32 (i32.const 464)) (global $TD_OL i32 (i32.const 3))
  (global $TD_C i32 (i32.const 467)) (global $TD_CL i32 (i32.const 5))
  (global $ALIGN i32 (i32.const 472)) (global $ALIGNL i32 (i32.const 8))
  (global $QUOT i32 (i32.const 480)) (global $QUOTL i32 (i32.const 1))
  (global $CBX i32 (i32.const 481)) (global $CBXL i32 (i32.const 31))
  (global $CHECKED i32 (i32.const 512)) (global $CHECKEDL i32 (i32.const 8))
  (global $CBX_END i32 (i32.const 520)) (global $CBX_ENDL i32 (i32.const 2))
  (global $CODE_O i32 (i32.const 522)) (global $CODE_OL i32 (i32.const 6))
  (global $CODE_C i32 (i32.const 528)) (global $CODE_CL i32 (i32.const 7))
  (global $A_O i32 (i32.const 535)) (global $A_OL i32 (i32.const 9))
  (global $A_MID i32 (i32.const 544)) (global $A_MIDL i32 (i32.const 2))
  (global $A_C i32 (i32.const 546)) (global $A_CL i32 (i32.const 4))
  (global $IMG_O i32 (i32.const 550)) (global $IMG_OL i32 (i32.const 10))
  (global $IMG_ALT i32 (i32.const 560)) (global $IMG_ALTL i32 (i32.const 7))
  (global $IMG_C i32 (i32.const 567)) (global $IMG_CL i32 (i32.const 2))
  (global $STRONG_O i32 (i32.const 569)) (global $STRONG_OL i32 (i32.const 8))
  (global $STRONG_C i32 (i32.const 577)) (global $STRONG_CL i32 (i32.const 9))
  (global $EM_O i32 (i32.const 586)) (global $EM_OL i32 (i32.const 4))
  (global $EM_C i32 (i32.const 590)) (global $EM_CL i32 (i32.const 5))
  (global $DEL_O i32 (i32.const 595)) (global $DEL_OL i32 (i32.const 5))
  (global $DEL_C i32 (i32.const 600)) (global $DEL_CL i32 (i32.const 6))
  (global $AMP i32 (i32.const 606)) (global $AMPL i32 (i32.const 5))
  (global $LT i32 (i32.const 611)) (global $LTL i32 (i32.const 4))
  (global $GT i32 (i32.const 615)) (global $GTL i32 (i32.const 4))
  (global $QUOT_E i32 (i32.const 619)) (global $QUOT_EL i32 (i32.const 6))
  (global $HASH i32 (i32.const 625)) (global $HASHL i32 (i32.const 1))
  (global $JS i32 (i32.const 626)) (global $JSL i32 (i32.const 10))
  (global $VBS i32 (i32.const 636)) (global $VBSL i32 (i32.const 8))
  (global $HTTP i32 (i32.const 644)) (global $HTTPL i32 (i32.const 4))

  ;; ===================== low-level helpers =====================

  ;; copy len bytes from ptr to $op, advance $op
  (func $put (param $ptr i32) (param $len i32)
    (memory.copy (global.get $op) (local.get $ptr) (local.get $len))
    (global.set $op (i32.add (global.get $op) (local.get $len))))

  ;; emit single byte to $op
  (func $putb (param $b i32)
    (i32.store8 (global.get $op) (local.get $b))
    (global.set $op (i32.add (global.get $op) (i32.const 1))))

  (func $isws (param $c i32) (result i32)
    (i32.or
      (i32.eq (local.get $c) (i32.const 32))
      (i32.and (i32.ge_u (local.get $c) (i32.const 9))
               (i32.le_u (local.get $c) (i32.const 13)))))

  (func $isdigit (param $c i32) (result i32)
    (i32.and (i32.ge_u (local.get $c) (i32.const 48))
             (i32.le_u (local.get $c) (i32.const 57))))

  (func $isword (param $c i32) (result i32)
    (i32.or (call $isdigit (local.get $c))
      (i32.or (i32.eq (local.get $c) (i32.const 95))
        (i32.or
          (i32.and (i32.ge_u (local.get $c) (i32.const 65)) (i32.le_u (local.get $c) (i32.const 90)))
          (i32.and (i32.ge_u (local.get $c) (i32.const 97)) (i32.le_u (local.get $c) (i32.const 122)))))))

  ;; write unsigned int n as decimal at buf; return byte count
  (func $wr_num (param $buf i32) (param $n i32) (result i32)
    (local $len i32) (local $t i32) (local $i i32) (local $d i32)
    (if (i32.eqz (local.get $n))
      (then (i32.store8 (local.get $buf) (i32.const 48)) (return (i32.const 1))))
    ;; count digits
    (local.set $t (local.get $n)) (local.set $len (i32.const 0))
    (block $done (loop $l
      (br_if $done (i32.eqz (local.get $t)))
      (local.set $t (i32.div_u (local.get $t) (i32.const 10)))
      (local.set $len (i32.add (local.get $len) (i32.const 1)))
      (br $l)))
    ;; write digits back-to-front
    (local.set $t (local.get $n)) (local.set $i (local.get $len))
    (block $d2 (loop $l2
      (br_if $d2 (i32.eqz (local.get $t)))
      (local.set $i (i32.sub (local.get $i) (i32.const 1)))
      (local.set $d (i32.rem_u (local.get $t) (i32.const 10)))
      (i32.store8 (i32.add (local.get $buf) (local.get $i)) (i32.add (local.get $d) (i32.const 48)))
      (local.set $t (i32.div_u (local.get $t) (i32.const 10)))
      (br $l2)))
    (local.get $len))

  (func $emit_num (param $n i32)
    (global.set $op (i32.add (global.get $op) (call $wr_num (global.get $op) (local.get $n)))))

  ;; copy literal/bytes to local cursor, return advanced cursor
  (func $cl (param $o i32) (param $p i32) (param $l i32) (result i32)
    (memory.copy (local.get $o) (local.get $p) (local.get $l))
    (i32.add (local.get $o) (local.get $l)))
  (func $cb (param $o i32) (param $b i32) (result i32)
    (i32.store8 (local.get $o) (local.get $b))
    (i32.add (local.get $o) (i32.const 1)))

  ;; ===================== inline stash =====================
  (func $stashb (param $p i32) (param $l i32)
    (memory.copy (global.get $stb) (local.get $p) (local.get $l))
    (global.set $stb (i32.add (global.get $stb) (local.get $l))))
  (func $stash_finalize (param $start i32) (result i32)
    (local $idx i32)
    (local.set $idx (global.get $stc))
    (i32.store (i32.add (global.get $STASHT) (i32.mul (local.get $idx) (i32.const 8))) (local.get $start))
    (i32.store (i32.add (global.get $STASHT) (i32.add (i32.mul (local.get $idx) (i32.const 8)) (i32.const 4)))
               (i32.sub (global.get $stb) (local.get $start)))
    (global.set $stc (i32.add (local.get $idx) (i32.const 1)))
    (local.get $idx))
  ;; write \0 idx \0 placeholder at o, return advanced cursor
  (func $wr_ph2 (param $o i32) (param $idx i32) (result i32)
    (local.set $o (call $cb (local.get $o) (i32.const 0)))
    (local.set $o (i32.add (local.get $o) (call $wr_num (local.get $o) (local.get $idx))))
    (call $cb (local.get $o) (i32.const 0)))

  ;; case-insensitive compare (bp lowercase); n bytes
  (func $ci (param $ap i32) (param $bp i32) (param $n i32) (result i32)
    (local $i i32)
    (block $f (loop $l
      (br_if $f (i32.ge_u (local.get $i) (local.get $n)))
      (if (i32.ne (i32.or (i32.load8_u (i32.add (local.get $ap) (local.get $i))) (i32.const 0x20))
                  (i32.load8_u (i32.add (local.get $bp) (local.get $i))))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
    (i32.const 1))

  (func $isjsvbs (param $up i32) (param $ul i32) (result i32)
    (local $i i32)
    (block $s (loop $sl
      (br_if $s (i32.ge_u (local.get $i) (local.get $ul)))
      (br_if $s (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $up) (local.get $i))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $sl)))
    (if (i32.le_u (i32.add (local.get $i) (i32.const 11)) (local.get $ul))
      (then (if (i32.and (call $ci (i32.add (local.get $up) (local.get $i)) (global.get $JS) (i32.const 10))
                         (i32.eq (i32.load8_u (i32.add (local.get $up) (i32.add (local.get $i) (i32.const 10)))) (i32.const 58)))
              (then (return (i32.const 1))))))
    (if (i32.le_u (i32.add (local.get $i) (i32.const 9)) (local.get $ul))
      (then (if (i32.and (call $ci (i32.add (local.get $up) (local.get $i)) (global.get $VBS) (i32.const 8))
                         (i32.eq (i32.load8_u (i32.add (local.get $up) (i32.add (local.get $i) (i32.const 8)))) (i32.const 58)))
              (then (return (i32.const 1))))))
    (i32.const 0))

  (func $stash_url (param $up i32) (param $ul i32)
    (if (call $isjsvbs (local.get $up) (local.get $ul))
      (then (call $stashb (global.get $HASH) (i32.const 1)))
      (else (call $stashb (local.get $up) (local.get $ul)))))

  ;; ===================== pass 1: escape =====================
  (func $esc (param $inp i32) (param $inl i32) (param $outp i32) (result i32)
    (local $i i32) (local $o i32) (local $c i32) (local $k i32)
    (local.set $o (local.get $outp))
    (block $end (loop $lp
      (br_if $end (i32.ge_u (local.get $i) (local.get $inl)))
      (local.set $c (i32.load8_u (i32.add (local.get $inp) (local.get $i))))
      (if (i32.eq (local.get $c) (i32.const 38)) ;; &
        (then
          (local.set $k (i32.add (local.get $i) (i32.const 1)))
          (block $ke (loop $kl
            (br_if $ke (i32.ge_u (local.get $k) (local.get $inl)))
            (local.set $c (i32.load8_u (i32.add (local.get $inp) (local.get $k))))
            (br_if $ke (i32.eqz (i32.or (i32.eq (local.get $c) (i32.const 35)) (call $isword (local.get $c)))))
            (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $kl)))
          (if (i32.and (i32.gt_u (local.get $k) (i32.add (local.get $i) (i32.const 1)))
                (i32.and (i32.lt_u (local.get $k) (local.get $inl))
                         (i32.eq (i32.load8_u (i32.add (local.get $inp) (local.get $k))) (i32.const 59))))
            (then (local.set $o (call $cb (local.get $o) (i32.const 38))))
            (else (local.set $o (call $cl (local.get $o) (global.get $AMP) (global.get $AMPL)))))
          (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
      (if (i32.eq (local.get $c) (i32.const 60))
        (then (local.set $o (call $cl (local.get $o) (global.get $LT) (global.get $LTL)))
              (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
      (if (i32.eq (local.get $c) (i32.const 62))
        (then (local.set $o (call $cl (local.get $o) (global.get $GT) (global.get $GTL)))
              (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
      (if (i32.eq (local.get $c) (i32.const 34))
        (then (local.set $o (call $cl (local.get $o) (global.get $QUOT_E) (global.get $QUOT_EL)))
              (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
      (local.set $o (call $cb (local.get $o) (local.get $c)))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
    (i32.sub (local.get $o) (local.get $outp)))

  ;; ===================== pass 2: code spans =====================
  (func $pcode (param $inp i32) (param $inl i32) (param $outp i32) (result i32)
    (local $i i32) (local $o i32) (local $j i32) (local $st i32) (local $idx i32)
    (local.set $o (local.get $outp))
    (block $end (loop $lp
      (br_if $end (i32.ge_u (local.get $i) (local.get $inl)))
      (if (i32.eq (i32.load8_u (i32.add (local.get $inp) (local.get $i))) (i32.const 96))
        (then
          (local.set $j (i32.add (local.get $i) (i32.const 1)))
          (block $fe (loop $fl
            (br_if $fe (i32.ge_u (local.get $j) (local.get $inl)))
            (br_if $fe (i32.eq (i32.load8_u (i32.add (local.get $inp) (local.get $j))) (i32.const 96)))
            (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $fl)))
          (if (i32.and (i32.lt_u (local.get $j) (local.get $inl))
                       (i32.gt_u (local.get $j) (i32.add (local.get $i) (i32.const 1))))
            (then
              (local.set $st (global.get $stb))
              (call $stashb (global.get $CODE_O) (global.get $CODE_OL))
              (call $stashb (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 1)))
                            (i32.sub (local.get $j) (i32.add (local.get $i) (i32.const 1))))
              (call $stashb (global.get $CODE_C) (global.get $CODE_CL))
              (local.set $idx (call $stash_finalize (local.get $st)))
              (local.set $o (call $wr_ph2 (local.get $o) (local.get $idx)))
              (local.set $i (i32.add (local.get $j) (i32.const 1))) (br $lp))
            (else
              (local.set $o (call $cb (local.get $o) (i32.const 96)))
              (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))))
      (local.set $o (call $cb (local.get $o) (i32.load8_u (i32.add (local.get $inp) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
    (i32.sub (local.get $o) (local.get $outp)))

  ;; ===================== pass 3: links & images =====================
  (func $plinks (param $inp i32) (param $inl i32) (param $outp i32) (result i32)
    (local $i i32) (local $o i32) (local $c i32) (local $b i32) (local $br0 i32)
    (local $tp i32) (local $p i32) (local $us i32) (local $ue i32) (local $ma i32)
    (local $st i32) (local $idx i32)
    (local.set $o (local.get $outp))
    (block $end (loop $lp
      (br_if $end (i32.ge_u (local.get $i) (local.get $inl)))
      (local.set $c (i32.load8_u (i32.add (local.get $inp) (local.get $i))))
      (local.set $b (i32.const -1))
      (if (i32.and (i32.eq (local.get $c) (i32.const 33))
                   (i32.and (i32.lt_u (i32.add (local.get $i) (i32.const 1)) (local.get $inl))
                            (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 1)))) (i32.const 91))))
        (then (local.set $b (i32.const 1)) (local.set $br0 (i32.add (local.get $i) (i32.const 1)))))
      (if (i32.eq (local.get $c) (i32.const 91))
        (then (local.set $b (i32.const 0)) (local.set $br0 (local.get $i))))
      (block $fail
        (if (i32.lt_s (local.get $b) (i32.const 0)) (then (br $fail)))
        ;; text [^\]]*
        (local.set $tp (i32.add (local.get $br0) (i32.const 1)))
        (block $te (loop $tl
          (br_if $te (i32.ge_u (local.get $tp) (local.get $inl)))
          (br_if $te (i32.eq (i32.load8_u (i32.add (local.get $inp) (local.get $tp))) (i32.const 93)))
          (local.set $tp (i32.add (local.get $tp) (i32.const 1))) (br $tl)))
        (if (i32.or (i32.ge_u (local.get $tp) (local.get $inl))
                    (i32.ne (i32.load8_u (i32.add (local.get $inp) (local.get $tp))) (i32.const 93)))
          (then (br $fail)))
        ;; '(' after ']'
        (local.set $p (i32.add (local.get $tp) (i32.const 1)))
        (if (i32.or (i32.ge_u (local.get $p) (local.get $inl))
                    (i32.ne (i32.load8_u (i32.add (local.get $inp) (local.get $p))) (i32.const 40)))
          (then (br $fail)))
        (local.set $p (i32.add (local.get $p) (i32.const 1)))
        ;; skip \s*
        (block $we (loop $wl
          (br_if $we (i32.ge_u (local.get $p) (local.get $inl)))
          (br_if $we (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $inp) (local.get $p))))))
          (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $wl)))
        (local.set $us (local.get $p))
        ;; url subpattern
        (local.set $ma (i32.const 0))
        (block $ue2 (loop $ul
          (br_if $ue2 (i32.ge_u (local.get $p) (local.get $inl)))
          (local.set $c (i32.load8_u (i32.add (local.get $inp) (local.get $p))))
          (if (i32.eq (local.get $c) (i32.const 40))
            (then
              (local.set $p (i32.add (local.get $p) (i32.const 1)))
              (block $pe (loop $pl
                (br_if $pe (i32.ge_u (local.get $p) (local.get $inl)))
                (br_if $pe (i32.eq (i32.load8_u (i32.add (local.get $inp) (local.get $p))) (i32.const 41)))
                (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $pl)))
              (if (i32.lt_u (local.get $p) (local.get $inl)) (then (local.set $p (i32.add (local.get $p) (i32.const 1)))))
              (local.set $ma (i32.const 1)) (br $ul)))
          (br_if $ue2 (i32.or (i32.eq (local.get $c) (i32.const 41))
                        (i32.or (call $isws (local.get $c)) (i32.eqz (local.get $c)))))
          (local.set $p (i32.add (local.get $p) (i32.const 1)))
          (local.set $ma (i32.const 1)) (br $ul)))
        (local.set $ue (local.get $p))
        (if (i32.eqz (local.get $ma)) (then (br $fail)))
        ;; [^)]* until )
        (block $ce (loop $cl3
          (br_if $ce (i32.ge_u (local.get $p) (local.get $inl)))
          (br_if $ce (i32.eq (i32.load8_u (i32.add (local.get $inp) (local.get $p))) (i32.const 41)))
          (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $cl3)))
        (if (i32.ge_u (local.get $p) (local.get $inl)) (then (br $fail)))
        ;; SUCCESS
        (if (i32.eq (local.get $b) (i32.const 1))
          (then
            (local.set $st (global.get $stb))
            (call $stashb (global.get $IMG_O) (global.get $IMG_OL))
            (call $stash_url (i32.add (local.get $inp) (local.get $us)) (i32.sub (local.get $ue) (local.get $us)))
            (call $stashb (global.get $IMG_ALT) (global.get $IMG_ALTL))
            (call $stashb (i32.add (local.get $inp) (i32.add (local.get $br0) (i32.const 1)))
                          (i32.sub (local.get $tp) (i32.add (local.get $br0) (i32.const 1))))
            (call $stashb (global.get $IMG_C) (global.get $IMG_CL))
            (local.set $idx (call $stash_finalize (local.get $st)))
            (local.set $o (call $wr_ph2 (local.get $o) (local.get $idx))))
          (else
            (local.set $st (global.get $stb))
            (call $stashb (global.get $A_O) (global.get $A_OL))
            (call $stash_url (i32.add (local.get $inp) (local.get $us)) (i32.sub (local.get $ue) (local.get $us)))
            (call $stashb (global.get $A_MID) (global.get $A_MIDL))
            (local.set $idx (call $stash_finalize (local.get $st)))
            (local.set $o (call $wr_ph2 (local.get $o) (local.get $idx)))
            (memory.copy (local.get $o) (i32.add (local.get $inp) (i32.add (local.get $br0) (i32.const 1)))
                         (i32.sub (local.get $tp) (i32.add (local.get $br0) (i32.const 1))))
            (local.set $o (i32.add (local.get $o) (i32.sub (local.get $tp) (i32.add (local.get $br0) (i32.const 1)))))
            (local.set $st (global.get $stb))
            (call $stashb (global.get $A_C) (global.get $A_CL))
            (local.set $idx (call $stash_finalize (local.get $st)))
            (local.set $o (call $wr_ph2 (local.get $o) (local.get $idx)))))
        (local.set $i (i32.add (local.get $p) (i32.const 1))) (br $lp))
      ;; fail: emit one byte
      (local.set $o (call $cb (local.get $o) (i32.load8_u (i32.add (local.get $inp) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
    (i32.sub (local.get $o) (local.get $outp)))

  ;; ===================== pass 4: bare-url autolink =====================
  (func $scheme (param $inp i32) (param $i i32) (param $inl i32) (result i32)
    (if (i32.gt_u (i32.add (local.get $i) (i32.const 7)) (local.get $inl)) (then (return (i32.const 0))))
    (if (i32.eqz (call $ci (i32.add (local.get $inp) (local.get $i)) (global.get $HTTP) (i32.const 4))) (then (return (i32.const 0))))
    (if (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 4)))) (i32.const 115)) ;; s
      (then (return (i32.and (i32.le_u (i32.add (local.get $i) (i32.const 8)) (local.get $inl))
              (i32.and (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 5)))) (i32.const 58))
                (i32.and (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 6)))) (i32.const 47))
                         (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 7)))) (i32.const 47))))))))
    (i32.and (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 4)))) (i32.const 58))
      (i32.and (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 5)))) (i32.const 47))
               (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 6)))) (i32.const 47)))))

  (func $urlstop (param $c i32) (result i32)
    (i32.or (call $isws (local.get $c))
      (i32.or (i32.eqz (local.get $c))
        (i32.or (i32.eq (local.get $c) (i32.const 60))   ;; <
          (i32.or (i32.eq (local.get $c) (i32.const 41)) ;; )
            (i32.or (i32.eq (local.get $c) (i32.const 34))   ;; "
                    (i32.eq (local.get $c) (i32.const 39)))))))) ;; '

  (func $ispunct (param $c i32) (result i32)
    (i32.or (i32.eq (local.get $c) (i32.const 46)) ;; .
      (i32.or (i32.eq (local.get $c) (i32.const 44)) ;; ,
        (i32.or (i32.eq (local.get $c) (i32.const 59)) ;; ;
          (i32.or (i32.eq (local.get $c) (i32.const 58)) ;; :
            (i32.or (i32.eq (local.get $c) (i32.const 33)) ;; !
                    (i32.eq (local.get $c) (i32.const 63)))))))) ;; ?

  (func $purls (param $inp i32) (param $inl i32) (param $outp i32) (result i32)
    (local $i i32) (local $o i32) (local $us i32) (local $p i32) (local $te i32)
    (local $st i32) (local $idx i32) (local $bnd i32)
    (local.set $o (local.get $outp))
    (block $end (loop $lp
      (br_if $end (i32.ge_u (local.get $i) (local.get $inl)))
      (local.set $bnd (i32.or (i32.eqz (local.get $i))
        (i32.or (call $isws (i32.load8_u (i32.add (local.get $inp) (i32.sub (local.get $i) (i32.const 1)))))
                (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.sub (local.get $i) (i32.const 1)))) (i32.const 40)))))
      (if (i32.and (local.get $bnd) (call $scheme (local.get $inp) (local.get $i) (local.get $inl)))
        (then
          (local.set $us (local.get $i))
          (local.set $p (local.get $i))
          (block $se (loop $sl
            (br_if $se (i32.ge_u (local.get $p) (local.get $inl)))
            (br_if $se (call $urlstop (i32.load8_u (i32.add (local.get $inp) (local.get $p)))))
            (local.set $p (i32.add (local.get $p) (i32.const 1))) (br $sl)))
          (local.set $te (local.get $p))
          (block $pe (loop $pl
            (br_if $pe (i32.le_u (local.get $te) (local.get $us)))
            (br_if $pe (i32.eqz (call $ispunct (i32.load8_u (i32.add (local.get $inp) (i32.sub (local.get $te) (i32.const 1)))))))
            (local.set $te (i32.sub (local.get $te) (i32.const 1))) (br $pl)))
          (local.set $st (global.get $stb))
          (call $stashb (global.get $A_O) (global.get $A_OL))
          (call $stashb (i32.add (local.get $inp) (local.get $us)) (i32.sub (local.get $te) (local.get $us)))
          (call $stashb (global.get $A_MID) (global.get $A_MIDL))
          (call $stashb (i32.add (local.get $inp) (local.get $us)) (i32.sub (local.get $te) (local.get $us)))
          (call $stashb (global.get $A_C) (global.get $A_CL))
          (local.set $idx (call $stash_finalize (local.get $st)))
          (local.set $o (call $wr_ph2 (local.get $o) (local.get $idx)))
          (memory.copy (local.get $o) (i32.add (local.get $inp) (local.get $te)) (i32.sub (local.get $p) (local.get $te)))
          (local.set $o (i32.add (local.get $o) (i32.sub (local.get $p) (local.get $te))))
          (local.set $i (local.get $p)) (br $lp)))
      (local.set $o (call $cb (local.get $o) (i32.load8_u (i32.add (local.get $inp) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
    (i32.sub (local.get $o) (local.get $outp)))

  ;; ===================== pass 5: emphasis =====================
  (func $pem (param $inp i32) (param $inl i32) (param $outp i32) (result i32)
    (local $i i32) (local $o i32) (local $r i32) (local $n i32)
    (local $cs i32) (local $ce i32) (local $s i32)
    (local.set $o (local.get $outp))
    (block $end (loop $lp
      (br_if $end (i32.ge_u (local.get $i) (local.get $inl)))
      (if (i32.ne (i32.load8_u (i32.add (local.get $inp) (local.get $i))) (i32.const 42))
        (then
          (local.set $o (call $cb (local.get $o) (i32.load8_u (i32.add (local.get $inp) (local.get $i)))))
          (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
      (local.set $r (i32.const 0))
      (block $re (loop $rl
        (br_if $re (i32.ge_u (i32.add (local.get $i) (local.get $r)) (local.get $inl)))
        (br_if $re (i32.ne (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (local.get $r)))) (i32.const 42)))
        (local.set $r (i32.add (local.get $r) (i32.const 1))) (br $rl)))
      (local.set $n (select (i32.const 3) (local.get $r) (i32.gt_u (local.get $r) (i32.const 3))))
      (block $matched
        (block $nomatch
          (loop $nl
            (br_if $nomatch (i32.eqz (local.get $n)))
            (local.set $cs (i32.add (local.get $i) (local.get $n)))
            (if (i32.and (i32.lt_u (local.get $cs) (local.get $inl))
                         (i32.ne (i32.load8_u (i32.add (local.get $inp) (local.get $cs))) (i32.const 42)))
              (then
                (local.set $ce (local.get $cs))
                (block $cce (loop $ccl
                  (br_if $cce (i32.ge_u (local.get $ce) (local.get $inl)))
                  (br_if $cce (i32.eq (i32.load8_u (i32.add (local.get $inp) (local.get $ce))) (i32.const 42)))
                  (local.set $ce (i32.add (local.get $ce) (i32.const 1))) (br $ccl)))
                (local.set $s (local.get $ce))
                (block $sse (loop $ssl
                  (br_if $sse (i32.ge_u (local.get $s) (local.get $inl)))
                  (br_if $sse (i32.ne (i32.load8_u (i32.add (local.get $inp) (local.get $s))) (i32.const 42)))
                  (local.set $s (i32.add (local.get $s) (i32.const 1))) (br $ssl)))
                (if (i32.ge_u (i32.sub (local.get $s) (local.get $ce)) (local.get $n))
                  (then
                    (if (i32.eq (local.get $n) (i32.const 3))
                      (then (local.set $o (call $cl (local.get $o) (global.get $STRONG_O) (global.get $STRONG_OL)))
                            (local.set $o (call $cl (local.get $o) (global.get $EM_O) (global.get $EM_OL)))))
                    (if (i32.eq (local.get $n) (i32.const 2))
                      (then (local.set $o (call $cl (local.get $o) (global.get $STRONG_O) (global.get $STRONG_OL)))))
                    (if (i32.eq (local.get $n) (i32.const 1))
                      (then (local.set $o (call $cl (local.get $o) (global.get $EM_O) (global.get $EM_OL)))))
                    (memory.copy (local.get $o) (i32.add (local.get $inp) (local.get $cs)) (i32.sub (local.get $ce) (local.get $cs)))
                    (local.set $o (i32.add (local.get $o) (i32.sub (local.get $ce) (local.get $cs))))
                    (if (i32.eq (local.get $n) (i32.const 1))
                      (then (local.set $o (call $cl (local.get $o) (global.get $EM_C) (global.get $EM_CL)))))
                    (if (i32.eq (local.get $n) (i32.const 2))
                      (then (local.set $o (call $cl (local.get $o) (global.get $STRONG_C) (global.get $STRONG_CL)))))
                    (if (i32.eq (local.get $n) (i32.const 3))
                      (then (local.set $o (call $cl (local.get $o) (global.get $EM_C) (global.get $EM_CL)))
                            (local.set $o (call $cl (local.get $o) (global.get $STRONG_C) (global.get $STRONG_CL)))))
                    (local.set $i (i32.add (local.get $ce) (local.get $n)))
                    (br $matched)))))
            (local.set $n (i32.sub (local.get $n) (i32.const 1))) (br $nl)))
        (local.set $o (call $cb (local.get $o) (i32.const 42)))
        (local.set $i (i32.add (local.get $i) (i32.const 1))))
      (br $lp)))
    (i32.sub (local.get $o) (local.get $outp)))

  ;; ===================== pass 6: strikethrough =====================
  (func $pstrike (param $inp i32) (param $inl i32) (param $outp i32) (result i32)
    (local $i i32) (local $o i32) (local $cs i32) (local $ce i32)
    (local.set $o (local.get $outp))
    (block $end (loop $lp
      (br_if $end (i32.ge_u (local.get $i) (local.get $inl)))
      (if (i32.and (i32.eq (i32.load8_u (i32.add (local.get $inp) (local.get $i))) (i32.const 126))
                   (i32.and (i32.lt_u (i32.add (local.get $i) (i32.const 1)) (local.get $inl))
                            (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $i) (i32.const 1)))) (i32.const 126))))
        (then
          (local.set $cs (i32.add (local.get $i) (i32.const 2)))
          (local.set $ce (local.get $cs))
          (block $ce2 (loop $cl2
            (br_if $ce2 (i32.ge_u (local.get $ce) (local.get $inl)))
            (br_if $ce2 (i32.eq (i32.load8_u (i32.add (local.get $inp) (local.get $ce))) (i32.const 126)))
            (local.set $ce (i32.add (local.get $ce) (i32.const 1))) (br $cl2)))
          (if (i32.and (i32.gt_u (local.get $ce) (local.get $cs))
                (i32.and (i32.lt_u (i32.add (local.get $ce) (i32.const 1)) (local.get $inl))
                         (i32.eq (i32.load8_u (i32.add (local.get $inp) (i32.add (local.get $ce) (i32.const 1)))) (i32.const 126))))
            (then
              (local.set $o (call $cl (local.get $o) (global.get $DEL_O) (global.get $DEL_OL)))
              (memory.copy (local.get $o) (i32.add (local.get $inp) (local.get $cs)) (i32.sub (local.get $ce) (local.get $cs)))
              (local.set $o (i32.add (local.get $o) (i32.sub (local.get $ce) (local.get $cs))))
              (local.set $o (call $cl (local.get $o) (global.get $DEL_C) (global.get $DEL_CL)))
              (local.set $i (i32.add (local.get $ce) (i32.const 2))) (br $lp))
            (else
              (local.set $o (call $cb (local.get $o) (i32.const 126)))
              (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))))
      (local.set $o (call $cb (local.get $o) (i32.load8_u (i32.add (local.get $inp) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp)))
    (i32.sub (local.get $o) (local.get $outp)))

  ;; ===================== restore placeholders → $op =====================
  (func $restore (param $inp i32) (param $inl i32)
    (local $i i32) (local $c i32) (local $n i32) (local $off i32) (local $len i32)
    (block $end (loop $lp
      (br_if $end (i32.ge_u (local.get $i) (local.get $inl)))
      (local.set $c (i32.load8_u (i32.add (local.get $inp) (local.get $i))))
      (if (i32.eqz (local.get $c))
        (then
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (local.set $n (i32.const 0))
          (block $pe (loop $pl
            (local.set $c (i32.load8_u (i32.add (local.get $inp) (local.get $i))))
            (br_if $pe (i32.eqz (local.get $c)))
            (local.set $n (i32.add (i32.mul (local.get $n) (i32.const 10)) (i32.sub (local.get $c) (i32.const 48))))
            (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $pl)))
          (local.set $i (i32.add (local.get $i) (i32.const 1)))
          (local.set $off (i32.load (i32.add (global.get $STASHT) (i32.mul (local.get $n) (i32.const 8)))))
          (local.set $len (i32.load (i32.add (global.get $STASHT) (i32.add (i32.mul (local.get $n) (i32.const 8)) (i32.const 4)))))
          (call $put (local.get $off) (local.get $len)) (br $lp)))
      (call $putb (local.get $c))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $lp))))

  ;; ===================== inline() → emits to $op =====================
  (func $inline (param $ptr i32) (param $len i32)
    (local $l i32)
    (global.set $stc (i32.const 0))
    (global.set $stb (global.get $STASHB0))
    (local.set $l (call $esc (local.get $ptr) (local.get $len) (global.get $W0)))
    (local.set $l (call $pcode (global.get $W0) (local.get $l) (global.get $W1)))
    (local.set $l (call $plinks (global.get $W1) (local.get $l) (global.get $W0)))
    (local.set $l (call $purls (global.get $W0) (local.get $l) (global.get $W1)))
    (local.set $l (call $pem (global.get $W1) (local.get $l) (global.get $W0)))
    (local.set $l (call $pstrike (global.get $W0) (local.get $l) (global.get $W1)))
    (call $restore (global.get $W1) (local.get $l)))

  ;; ===================== small scanners =====================
  (func $is_blank (param $ptr i32) (param $len i32) (result i32)
    (local $i i32)
    (block $f (loop $l
      (br_if $f (i32.ge_u (local.get $i) (local.get $len)))
      (br_if $f (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
    (i32.ge_u (local.get $i) (local.get $len)))

  (func $trimStart (param $ptr i32) (param $len i32)
    (local $i i32)
    (block $f (loop $l
      (br_if $f (i32.ge_u (local.get $i) (local.get $len)))
      (br_if $f (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
    (global.set $rp (i32.add (local.get $ptr) (local.get $i)))
    (global.set $rl (i32.sub (local.get $len) (local.get $i))))

  (func $contains_pipe (param $ptr i32) (param $len i32) (result i32)
    (local $i i32)
    (block $f (loop $l
      (br_if $f (i32.ge_u (local.get $i) (local.get $len)))
      (if (i32.eq (i32.load8_u (i32.add (local.get $ptr) (local.get $i))) (i32.const 124)) (then (return (i32.const 1))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
    (i32.const 0))

  ;; count leading ws; return count (caller checks <=3)
  (func $lead_ws (param $ptr i32) (param $len i32) (result i32)
    (local $i i32)
    (block $f (loop $l
      (br_if $f (i32.ge_u (local.get $i) (local.get $len)))
      (br_if $f (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
    (local.get $i))

  ;; ===================== block matchers (set $r*, return 1/0) =====================
  (func $m_fence_open (param $ptr i32) (param $len i32) (result i32)
    (local $w i32) (local $c i32) (local $k i32) (local $j i32)
    (local.set $w (call $lead_ws (local.get $ptr) (local.get $len)))
    (if (i32.gt_u (local.get $w) (i32.const 3)) (then (return (i32.const 0))))
    (if (i32.ge_u (local.get $w) (local.get $len)) (then (return (i32.const 0))))
    (local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $w))))
    (if (i32.and (i32.ne (local.get $c) (i32.const 96)) (i32.ne (local.get $c) (i32.const 126))) (then (return (i32.const 0))))
    (local.set $k (local.get $w))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $k) (local.get $len)))
      (br_if $e (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $k))) (local.get $c)))
      (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $l)))
    (if (i32.lt_u (i32.sub (local.get $k) (local.get $w)) (i32.const 3)) (then (return (i32.const 0))))
    (global.set $r0 (local.get $c))
    (global.set $r1 (i32.sub (local.get $k) (local.get $w)))
    ;; info: skip ws, take \S*
    (local.set $j (local.get $k))
    (block $e2 (loop $l2
      (br_if $e2 (i32.ge_u (local.get $j) (local.get $len)))
      (br_if $e2 (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $j))))))
      (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $l2)))
    (global.set $rp (i32.add (local.get $ptr) (local.get $j)))
    (local.set $k (local.get $j))
    (block $e3 (loop $l3
      (br_if $e3 (i32.ge_u (local.get $j) (local.get $len)))
      (br_if $e3 (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $j)))))
      (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $l3)))
    (global.set $rl (i32.sub (local.get $j) (local.get $k)))
    (i32.const 1))

  (func $m_fence_close (param $p i32) (param $ptr i32) (param $len i32) (result i32)
    (local $w i32) (local $c i32) (local $k i32) (local $j i32)
    (local.set $w (call $lead_ws (local.get $ptr) (local.get $len)))
    (if (i32.gt_u (local.get $w) (i32.const 3)) (then (return (i32.const 0))))
    (local.set $c (i32.load (i32.add (local.get $p) (i32.const 12)))) ;; FCH
    (if (i32.or (i32.ge_u (local.get $w) (local.get $len))
                (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $w))) (local.get $c))) (then (return (i32.const 0))))
    (local.set $k (local.get $w))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $k) (local.get $len)))
      (br_if $e (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $k))) (local.get $c)))
      (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $l)))
    (if (i32.lt_u (i32.sub (local.get $k) (local.get $w)) (i32.load (i32.add (local.get $p) (i32.const 16)))) (then (return (i32.const 0))))
    (local.set $j (local.get $k))
    (block $e2 (loop $l2
      (br_if $e2 (i32.ge_u (local.get $j) (local.get $len)))
      (br_if $e2 (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $j))))))
      (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $l2)))
    (i32.eq (local.get $j) (local.get $len)))

  (func $m_heading (param $ptr i32) (param $len i32) (result i32)
    (local $w i32) (local $L i32) (local $cp i32) (local $rs i32) (local $re i32)
    (local $p1 i32) (local $p2 i32) (local $p3 i32)
    (local.set $w (call $lead_ws (local.get $ptr) (local.get $len)))
    (if (i32.gt_u (local.get $w) (i32.const 3)) (then (return (i32.const 0))))
    (local.set $cp (local.get $w))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $cp) (local.get $len)))
      (br_if $e (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $cp))) (i32.const 35)))
      (local.set $cp (i32.add (local.get $cp) (i32.const 1))) (br $l)))
    (local.set $L (i32.sub (local.get $cp) (local.get $w)))
    (if (i32.or (i32.lt_u (local.get $L) (i32.const 1)) (i32.gt_u (local.get $L) (i32.const 6))) (then (return (i32.const 0))))
    ;; char after run must be ws or end
    (if (i32.lt_u (local.get $cp) (local.get $len))
      (then (if (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $cp))))) (then (return (i32.const 0))))))
    ;; skip ws → rest start
    (local.set $rs (local.get $cp))
    (block $e2 (loop $l2
      (br_if $e2 (i32.ge_u (local.get $rs) (local.get $len)))
      (br_if $e2 (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $rs))))))
      (local.set $rs (i32.add (local.get $rs) (i32.const 1))) (br $l2)))
    (local.set $re (local.get $len))
    ;; /\s+#*\s*$/
    (local.set $p1 (local.get $re))
    (block $a (loop $al (br_if $a (i32.le_u (local.get $p1) (local.get $rs)))
      (br_if $a (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (i32.sub (local.get $p1) (i32.const 1)))))))
      (local.set $p1 (i32.sub (local.get $p1) (i32.const 1))) (br $al)))
    (local.set $p2 (local.get $p1))
    (block $b (loop $bl (br_if $b (i32.le_u (local.get $p2) (local.get $rs)))
      (br_if $b (i32.ne (i32.load8_u (i32.add (local.get $ptr) (i32.sub (local.get $p2) (i32.const 1)))) (i32.const 35)))
      (local.set $p2 (i32.sub (local.get $p2) (i32.const 1))) (br $bl)))
    (local.set $p3 (local.get $p2))
    (block $d (loop $dl (br_if $d (i32.le_u (local.get $p3) (local.get $rs)))
      (br_if $d (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (i32.sub (local.get $p3) (i32.const 1)))))))
      (local.set $p3 (i32.sub (local.get $p3) (i32.const 1))) (br $dl)))
    (if (i32.lt_u (local.get $p3) (local.get $p2)) (then (local.set $re (local.get $p3))))
    ;; trimEnd
    (block $t (loop $tl (br_if $t (i32.le_u (local.get $re) (local.get $rs)))
      (br_if $t (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (i32.sub (local.get $re) (i32.const 1)))))))
      (local.set $re (i32.sub (local.get $re) (i32.const 1))) (br $tl)))
    (global.set $r0 (local.get $L))
    (global.set $rp (i32.add (local.get $ptr) (local.get $rs)))
    (global.set $rl (i32.sub (local.get $re) (local.get $rs)))
    (i32.const 1))

  (func $m_hr (param $ptr i32) (param $len i32) (result i32)
    (local $w i32) (local $c i32) (local $k i32) (local $j i32)
    (local.set $w (call $lead_ws (local.get $ptr) (local.get $len)))
    (if (i32.gt_u (local.get $w) (i32.const 3)) (then (return (i32.const 0))))
    (if (i32.ge_u (local.get $w) (local.get $len)) (then (return (i32.const 0))))
    (local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $w))))
    (if (i32.eqz (i32.or (i32.eq (local.get $c) (i32.const 45)) (i32.or (i32.eq (local.get $c) (i32.const 42)) (i32.eq (local.get $c) (i32.const 95)))))
      (then (return (i32.const 0))))
    (local.set $k (local.get $w))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $k) (local.get $len)))
      (br_if $e (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $k))) (local.get $c)))
      (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $l)))
    (if (i32.lt_u (i32.sub (local.get $k) (local.get $w)) (i32.const 3)) (then (return (i32.const 0))))
    (local.set $j (local.get $k))
    (block $e2 (loop $l2
      (br_if $e2 (i32.ge_u (local.get $j) (local.get $len)))
      (br_if $e2 (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $j))))))
      (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $l2)))
    (i32.eq (local.get $j) (local.get $len)))

  (func $m_bq (param $ptr i32) (param $len i32) (result i32)
    (local $w i32) (local $j i32)
    (local.set $w (call $lead_ws (local.get $ptr) (local.get $len)))
    (if (i32.gt_u (local.get $w) (i32.const 3)) (then (return (i32.const 0))))
    (if (i32.or (i32.ge_u (local.get $w) (local.get $len))
                (i32.ne (i32.load8_u (i32.add (local.get $ptr) (local.get $w))) (i32.const 62))) (then (return (i32.const 0))))
    (local.set $j (i32.add (local.get $w) (i32.const 1)))
    (if (i32.and (i32.lt_u (local.get $j) (local.get $len))
                 (i32.eq (i32.load8_u (i32.add (local.get $ptr) (local.get $j))) (i32.const 32)))
      (then (local.set $j (i32.add (local.get $j) (i32.const 1)))))
    (global.set $rp (i32.add (local.get $ptr) (local.get $j)))
    (global.set $rl (i32.sub (local.get $len) (local.get $j)))
    (i32.const 1))

  (func $m_list (param $ptr i32) (param $len i32) (result i32)
    (local $w i32) (local $j i32) (local $me i32) (local $ord i32) (local $st i32) (local $c i32) (local $rs i32)
    (local.set $w (call $lead_ws (local.get $ptr) (local.get $len)))
    (if (i32.ge_u (local.get $w) (local.get $len)) (then (return (i32.const 0))))
    (local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $w))))
    (if (call $isdigit (local.get $c))
      (then
        (local.set $j (local.get $w)) (local.set $st (i32.const 0))
        (block $e (loop $l
          (br_if $e (i32.ge_u (local.get $j) (local.get $len)))
          (local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $j))))
          (br_if $e (i32.eqz (call $isdigit (local.get $c))))
          (local.set $st (i32.add (i32.mul (local.get $st) (i32.const 10)) (i32.sub (local.get $c) (i32.const 48))))
          (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $l)))
        (if (i32.or (i32.ge_u (local.get $j) (local.get $len))
              (i32.eqz (i32.or (i32.eq (i32.load8_u (i32.add (local.get $ptr) (local.get $j))) (i32.const 46))
                               (i32.eq (i32.load8_u (i32.add (local.get $ptr) (local.get $j))) (i32.const 41)))))
          (then (return (i32.const 0))))
        (local.set $ord (i32.const 1)) (local.set $me (i32.add (local.get $j) (i32.const 1))))
      (else
        (if (i32.eqz (i32.or (i32.eq (local.get $c) (i32.const 45)) (i32.or (i32.eq (local.get $c) (i32.const 42)) (i32.eq (local.get $c) (i32.const 43)))))
          (then (return (i32.const 0))))
        (local.set $ord (i32.const 0)) (local.set $st (i32.const 0)) (local.set $me (i32.add (local.get $w) (i32.const 1)))))
    ;; require \s+
    (if (i32.or (i32.ge_u (local.get $me) (local.get $len))
                (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $me)))))) (then (return (i32.const 0))))
    (local.set $rs (local.get $me))
    (block $e2 (loop $l2
      (br_if $e2 (i32.ge_u (local.get $rs) (local.get $len)))
      (br_if $e2 (i32.eqz (call $isws (i32.load8_u (i32.add (local.get $ptr) (local.get $rs))))))
      (local.set $rs (i32.add (local.get $rs) (i32.const 1))) (br $l2)))
    (global.set $r0 (local.get $w))
    (global.set $r1 (local.get $ord))
    (global.set $r2 (local.get $st))
    (global.set $rp (i32.add (local.get $ptr) (local.get $rs)))
    (global.set $rl (i32.sub (local.get $len) (local.get $rs)))
    (i32.const 1))

  ;; ===================== record append =====================
  (func $rec_simple (param $p i32) (param $ptr i32) (param $len i32)
    (i32.store (global.get $arena) (local.get $len))
    (memory.copy (i32.add (global.get $arena) (i32.const 4)) (local.get $ptr) (local.get $len))
    (global.set $arena (i32.add (global.get $arena) (i32.add (local.get $len) (i32.const 4))))
    (i32.store (i32.add (local.get $p) (i32.const 24)) (i32.add (i32.load (i32.add (local.get $p) (i32.const 24))) (i32.const 1))))

  (func $rec_list (param $p i32) (param $ind i32) (param $ord i32) (param $st i32) (param $ptr i32) (param $len i32)
    (i32.store (global.get $arena) (local.get $ind))
    (i32.store (i32.add (global.get $arena) (i32.const 4)) (local.get $ord))
    (i32.store (i32.add (global.get $arena) (i32.const 8)) (local.get $st))
    (i32.store (i32.add (global.get $arena) (i32.const 12)) (local.get $len))
    (memory.copy (i32.add (global.get $arena) (i32.const 16)) (local.get $ptr) (local.get $len))
    (global.set $arena (i32.add (global.get $arena) (i32.add (local.get $len) (i32.const 16))))
    (i32.store (i32.add (local.get $p) (i32.const 24)) (i32.add (i32.load (i32.add (local.get $p) (i32.const 24))) (i32.const 1))))

  ;; ===================== renderers =====================
  (func $join_lines (param $p i32) (param $out i32) (result i32)
    (local $cur i32) (local $w i32) (local $k i32) (local $cnt i32) (local $rl i32)
    (local.set $cur (i32.load (i32.add (local.get $p) (i32.const 20))))
    (local.set $cnt (i32.load (i32.add (local.get $p) (i32.const 24))))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $k) (local.get $cnt)))
      (local.set $rl (i32.load (local.get $cur)))
      (memory.copy (i32.add (local.get $out) (local.get $w)) (i32.add (local.get $cur) (i32.const 4)) (local.get $rl))
      (local.set $w (i32.add (local.get $w) (local.get $rl)))
      (local.set $cur (i32.add (local.get $cur) (i32.add (local.get $rl) (i32.const 4))))
      (local.set $k (i32.add (local.get $k) (i32.const 1)))
      (if (i32.lt_u (local.get $k) (local.get $cnt))
        (then (i32.store8 (i32.add (local.get $out) (local.get $w)) (i32.const 10)) (local.set $w (i32.add (local.get $w) (i32.const 1)))))
      (br $l)))
    (local.get $w))

  (func $render_fence (param $p i32)
    (local $jl i32) (local $el i32)
    (call $put (global.get $PRE_O) (global.get $PRE_OL))
    (if (i32.gt_u (i32.load (i32.add (local.get $p) (i32.const 8))) (i32.const 0))
      (then (call $put (global.get $LANG) (global.get $LANGL))
            (call $put (i32.load (i32.add (local.get $p) (i32.const 4))) (i32.load (i32.add (local.get $p) (i32.const 8))))
            (call $put (global.get $TAG_C) (global.get $TAG_CL)))
      (else (call $put (global.get $H_MID) (global.get $H_MIDL))))
    (if (i32.gt_u (i32.load (i32.add (local.get $p) (i32.const 24))) (i32.const 0))
      (then
        (local.set $jl (call $join_lines (local.get $p) (global.get $JOIN)))
        (local.set $el (call $esc (global.get $JOIN) (local.get $jl) (global.get $op)))
        (global.set $op (i32.add (global.get $op) (local.get $el)))
        (call $putb (i32.const 10))))
    (call $put (global.get $PRE_C) (global.get $PRE_CL)))

  ;; iterate cells of a row; mode: 0=count/align(write to JOIN), 1=header th, 2=body td
  (func $render_row (param $rowp i32) (param $rowl i32) (param $mode i32) (param $ncol i32)
    (local $s i32) (local $e i32) (local $t i32) (local $cur i32) (local $col i32)
    (local $cs i32) (local $ce i32) (local $alc i32)
    (local.set $e (i32.add (local.get $rowp) (local.get $rowl)))
    ;; leading ws + optional pipe
    (local.set $t (local.get $rowp))
    (block $lw (loop $lwl (br_if $lw (i32.ge_u (local.get $t) (local.get $e)))
      (br_if $lw (i32.eqz (call $isws (i32.load8_u (local.get $t))))) (local.set $t (i32.add (local.get $t) (i32.const 1))) (br $lwl)))
    (if (i32.and (i32.lt_u (local.get $t) (local.get $e)) (i32.eq (i32.load8_u (local.get $t)) (i32.const 124)))
      (then (local.set $s (i32.add (local.get $t) (i32.const 1)))) (else (local.set $s (local.get $rowp))))
    ;; trailing ws + optional pipe
    (block $tw (loop $twl (br_if $tw (i32.le_u (local.get $e) (local.get $s)))
      (br_if $tw (i32.eqz (call $isws (i32.load8_u (i32.sub (local.get $e) (i32.const 1)))))) (local.set $e (i32.sub (local.get $e) (i32.const 1))) (br $twl)))
    (if (i32.and (i32.gt_u (local.get $e) (local.get $s)) (i32.eq (i32.load8_u (i32.sub (local.get $e) (i32.const 1))) (i32.const 124)))
      (then (local.set $e (i32.sub (local.get $e) (i32.const 1)))))
    (local.set $cur (local.get $s))
    (block $done (loop $cells
      (local.set $cs (local.get $cur))
      (block $ce2 (loop $cel (br_if $ce2 (i32.ge_u (local.get $cur) (local.get $e)))
        (br_if $ce2 (i32.eq (i32.load8_u (local.get $cur)) (i32.const 124))) (local.set $cur (i32.add (local.get $cur) (i32.const 1))) (br $cel)))
      (local.set $ce (local.get $cur))
      ;; trim cell [cs,ce)
      (block $tl (loop $tll (br_if $tl (i32.ge_u (local.get $cs) (local.get $ce)))
        (br_if $tl (i32.eqz (call $isws (i32.load8_u (local.get $cs))))) (local.set $cs (i32.add (local.get $cs) (i32.const 1))) (br $tll)))
      (block $tr (loop $trl (br_if $tr (i32.le_u (local.get $ce) (local.get $cs)))
        (br_if $tr (i32.eqz (call $isws (i32.load8_u (i32.sub (local.get $ce) (i32.const 1)))))) (local.set $ce (i32.sub (local.get $ce) (i32.const 1))) (br $trl)))
      (if (i32.eqz (local.get $mode))
        (then ;; compute align code
          (i32.store8 (i32.add (global.get $JOIN) (local.get $col))
            (if (result i32) (i32.eq (i32.load8_u (local.get $cs)) (i32.const 58))
              (then (if (result i32) (i32.eq (i32.load8_u (i32.sub (local.get $ce) (i32.const 1))) (i32.const 58)) (then (i32.const 3)) (else (i32.const 1))))
              (else (if (result i32) (i32.eq (i32.load8_u (i32.sub (local.get $ce) (i32.const 1))) (i32.const 58)) (then (i32.const 2)) (else (i32.const 0)))))))
        (else ;; render th/td
          (local.set $alc (if (result i32) (i32.lt_u (local.get $col) (local.get $ncol)) (then (i32.load8_u (i32.add (global.get $JOIN) (local.get $col)))) (else (i32.const 0))))
          (if (i32.eq (local.get $mode) (i32.const 1)) (then (call $put (global.get $TH_O) (global.get $TH_OL))) (else (call $put (global.get $TD_O) (global.get $TD_OL))))
          (if (i32.gt_u (local.get $alc) (i32.const 0))
            (then (call $put (global.get $ALIGN) (global.get $ALIGNL))
              (if (i32.eq (local.get $alc) (i32.const 1)) (then (call $put (i32.const 648) (i32.const 4))))
              (if (i32.eq (local.get $alc) (i32.const 2)) (then (call $put (i32.const 652) (i32.const 5))))
              (if (i32.eq (local.get $alc) (i32.const 3)) (then (call $put (i32.const 657) (i32.const 6))))
              (call $put (global.get $QUOT) (global.get $QUOTL))))
          (call $put (global.get $H_MID) (global.get $H_MIDL))
          (call $inline (local.get $cs) (i32.sub (local.get $ce) (local.get $cs)))
          (if (i32.eq (local.get $mode) (i32.const 1)) (then (call $put (global.get $TH_C) (global.get $TH_CL))) (else (call $put (global.get $TD_C) (global.get $TD_CL))))))
      (local.set $col (i32.add (local.get $col) (i32.const 1)))
      (if (i32.lt_u (local.get $cur) (local.get $e)) (then (local.set $cur (i32.add (local.get $cur) (i32.const 1))) (br $cells)))
      (br $done)))
    (global.set $r3 (local.get $col)))

  (func $is_delim_row (param $rowp i32) (param $rowl i32) (result i32)
    (local $s i32) (local $e i32) (local $t i32) (local $cur i32) (local $col i32)
    (local $cs i32) (local $ce i32) (local $q i32) (local $dsh i32)
    (local.set $e (i32.add (local.get $rowp) (local.get $rowl)))
    (local.set $t (local.get $rowp))
    (block $lw (loop $lwl (br_if $lw (i32.ge_u (local.get $t) (local.get $e)))
      (br_if $lw (i32.eqz (call $isws (i32.load8_u (local.get $t))))) (local.set $t (i32.add (local.get $t) (i32.const 1))) (br $lwl)))
    (if (i32.and (i32.lt_u (local.get $t) (local.get $e)) (i32.eq (i32.load8_u (local.get $t)) (i32.const 124)))
      (then (local.set $s (i32.add (local.get $t) (i32.const 1)))) (else (local.set $s (local.get $rowp))))
    (block $tw (loop $twl (br_if $tw (i32.le_u (local.get $e) (local.get $s)))
      (br_if $tw (i32.eqz (call $isws (i32.load8_u (i32.sub (local.get $e) (i32.const 1)))))) (local.set $e (i32.sub (local.get $e) (i32.const 1))) (br $twl)))
    (if (i32.and (i32.gt_u (local.get $e) (local.get $s)) (i32.eq (i32.load8_u (i32.sub (local.get $e) (i32.const 1))) (i32.const 124)))
      (then (local.set $e (i32.sub (local.get $e) (i32.const 1)))))
    (local.set $cur (local.get $s))
    (block $done (loop $cells
      (local.set $cs (local.get $cur))
      (block $ce2 (loop $cel (br_if $ce2 (i32.ge_u (local.get $cur) (local.get $e)))
        (br_if $ce2 (i32.eq (i32.load8_u (local.get $cur)) (i32.const 124))) (local.set $cur (i32.add (local.get $cur) (i32.const 1))) (br $cel)))
      (local.set $ce (local.get $cur))
      (block $tl (loop $tll (br_if $tl (i32.ge_u (local.get $cs) (local.get $ce)))
        (br_if $tl (i32.eqz (call $isws (i32.load8_u (local.get $cs))))) (local.set $cs (i32.add (local.get $cs) (i32.const 1))) (br $tll)))
      (block $tr (loop $trl (br_if $tr (i32.le_u (local.get $ce) (local.get $cs)))
        (br_if $tr (i32.eqz (call $isws (i32.load8_u (i32.sub (local.get $ce) (i32.const 1)))))) (local.set $ce (i32.sub (local.get $ce) (i32.const 1))) (br $trl)))
      ;; validate ^:?-+:?$
      (local.set $q (local.get $cs))
      (if (i32.and (i32.lt_u (local.get $q) (local.get $ce)) (i32.eq (i32.load8_u (local.get $q)) (i32.const 58))) (then (local.set $q (i32.add (local.get $q) (i32.const 1)))))
      (local.set $dsh (i32.const 0))
      (block $de (loop $dl (br_if $de (i32.ge_u (local.get $q) (local.get $ce)))
        (br_if $de (i32.ne (i32.load8_u (local.get $q)) (i32.const 45)))
        (local.set $q (i32.add (local.get $q) (i32.const 1))) (local.set $dsh (i32.add (local.get $dsh) (i32.const 1))) (br $dl)))
      (if (i32.lt_u (local.get $dsh) (i32.const 1)) (then (return (i32.const 0))))
      (if (i32.and (i32.lt_u (local.get $q) (local.get $ce)) (i32.eq (i32.load8_u (local.get $q)) (i32.const 58))) (then (local.set $q (i32.add (local.get $q) (i32.const 1)))))
      (if (i32.ne (local.get $q) (local.get $ce)) (then (return (i32.const 0))))
      (local.set $col (i32.add (local.get $col) (i32.const 1)))
      (if (i32.lt_u (local.get $cur) (local.get $e)) (then (local.set $cur (i32.add (local.get $cur) (i32.const 1))) (br $cells)))
      (br $done)))
    (i32.gt_u (local.get $col) (i32.const 0)))

  (func $render_table (param $p i32)
    (local $rec0 i32) (local $l0 i32) (local $rec1 i32) (local $l1 i32) (local $ncol i32)
    (local $cur i32) (local $k i32) (local $cnt i32) (local $rl i32)
    (local.set $rec0 (i32.load (i32.add (local.get $p) (i32.const 20))))
    (local.set $l0 (i32.load (local.get $rec0)))
    (local.set $rec1 (i32.add (local.get $rec0) (i32.add (local.get $l0) (i32.const 4))))
    (local.set $l1 (i32.load (local.get $rec1)))
    (call $render_row (i32.add (local.get $rec1) (i32.const 4)) (local.get $l1) (i32.const 0) (i32.const 0))
    (local.set $ncol (global.get $r3))
    (call $put (global.get $TBL_O) (global.get $TBL_OL))
    (call $render_row (i32.add (local.get $rec0) (i32.const 4)) (local.get $l0) (i32.const 1) (local.get $ncol))
    (call $put (global.get $THEAD_C) (global.get $THEAD_CL))
    (local.set $cur (i32.add (local.get $rec1) (i32.add (local.get $l1) (i32.const 4))))
    (local.set $cnt (i32.load (i32.add (local.get $p) (i32.const 24))))
    (local.set $k (i32.const 2))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $k) (local.get $cnt)))
      (local.set $rl (i32.load (local.get $cur)))
      (call $put (global.get $TR_O) (global.get $TR_OL))
      (call $render_row (i32.add (local.get $cur) (i32.const 4)) (local.get $rl) (i32.const 2) (local.get $ncol))
      (call $put (global.get $TR_C) (global.get $TR_CL))
      (local.set $cur (i32.add (local.get $cur) (i32.add (local.get $rl) (i32.const 4))))
      (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $l)))
    (call $put (global.get $TBL_C) (global.get $TBL_CL)))

  (func $render_para (param $p i32)
    (local $cnt i32) (local $rec0 i32) (local $l0 i32) (local $rec1 i32) (local $l1 i32) (local $jl i32)
    (local.set $cnt (i32.load (i32.add (local.get $p) (i32.const 24))))
    (if (i32.gt_u (local.get $cnt) (i32.const 1))
      (then
        (local.set $rec0 (i32.load (i32.add (local.get $p) (i32.const 20))))
        (local.set $l0 (i32.load (local.get $rec0)))
        (local.set $rec1 (i32.add (local.get $rec0) (i32.add (local.get $l0) (i32.const 4))))
        (local.set $l1 (i32.load (local.get $rec1)))
        (if (i32.and (call $contains_pipe (i32.add (local.get $rec0) (i32.const 4)) (local.get $l0))
                     (call $is_delim_row (i32.add (local.get $rec1) (i32.const 4)) (local.get $l1)))
          (then (call $render_table (local.get $p)) (return)))))
    (local.set $jl (call $join_lines (local.get $p) (global.get $JOIN)))
    (call $put (global.get $P_O) (global.get $P_OL))
    (call $inline (global.get $JOIN) (local.get $jl))
    (call $put (global.get $P_C) (global.get $P_CL)))

  (func $render_quote (param $p i32)
    (local $cur i32) (local $k i32) (local $cnt i32) (local $rl i32) (local $inner i32)
    (call $put (global.get $BQ_O) (global.get $BQ_OL))
    (local.set $inner (call $new_parser))
    (local.set $cur (i32.load (i32.add (local.get $p) (i32.const 20))))
    (local.set $cnt (i32.load (i32.add (local.get $p) (i32.const 24))))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $k) (local.get $cnt)))
      (local.set $rl (i32.load (local.get $cur)))
      (call $feed (local.get $inner) (i32.add (local.get $cur) (i32.const 4)) (local.get $rl))
      (local.set $cur (i32.add (local.get $cur) (i32.add (local.get $rl) (i32.const 4))))
      (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $l)))
    (call $close (local.get $inner))
    (call $put (global.get $BQ_C) (global.get $BQ_CL)))

  (func $render_list_range (param $lo i32) (param $hi i32)
    (local $rec0 i32) (local $ord i32) (local $start i32) (local $i i32) (local $j i32)
    (local $it i32) (local $ind i32) (local $tlen i32) (local $tptr i32) (local $b1 i32)
    (local.set $rec0 (i32.load (i32.add (global.get $JOIN) (i32.mul (local.get $lo) (i32.const 4)))))
    (local.set $ord (i32.load (i32.add (local.get $rec0) (i32.const 4))))
    (local.set $start (i32.load (i32.add (local.get $rec0) (i32.const 8))))
    (if (local.get $ord) (then (call $put (global.get $OL_O) (global.get $OL_OL))) (else (call $put (global.get $UL_O) (global.get $UL_OL))))
    (if (i32.gt_u (local.get $start) (i32.const 1))
      (then (call $put (global.get $START) (global.get $STARTL)) (call $emit_num (local.get $start)) (call $put (global.get $QUOT) (global.get $QUOTL))))
    (call $put (global.get $GT_NL) (global.get $GT_NLL))
    (local.set $i (local.get $lo))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $i) (local.get $hi)))
      (local.set $it (i32.load (i32.add (global.get $JOIN) (i32.mul (local.get $i) (i32.const 4)))))
      (local.set $ind (i32.load (local.get $it)))
      (local.set $j (i32.add (local.get $i) (i32.const 1)))
      (block $ke (loop $kl
        (br_if $ke (i32.ge_u (local.get $j) (local.get $hi)))
        (br_if $ke (i32.le_s (i32.load (i32.load (i32.add (global.get $JOIN) (i32.mul (local.get $j) (i32.const 4))))) (local.get $ind)))
        (local.set $j (i32.add (local.get $j) (i32.const 1))) (br $kl)))
      (call $put (global.get $LI_O) (global.get $LI_OL))
      (local.set $tlen (i32.load (i32.add (local.get $it) (i32.const 12))))
      (local.set $tptr (i32.add (local.get $it) (i32.const 16)))
      (local.set $b1 (i32.const 0))
      (if (i32.ge_u (local.get $tlen) (i32.const 4))
        (then (if (i32.and (i32.eq (i32.load8_u (local.get $tptr)) (i32.const 91))
                    (i32.and (i32.eq (i32.load8_u (i32.add (local.get $tptr) (i32.const 2))) (i32.const 93))
                             (i32.eq (i32.load8_u (i32.add (local.get $tptr) (i32.const 3))) (i32.const 32))))
                (then (local.set $b1 (i32.load8_u (i32.add (local.get $tptr) (i32.const 1))))
                      (if (i32.eqz (i32.or (i32.eq (local.get $b1) (i32.const 32)) (i32.or (i32.eq (local.get $b1) (i32.const 120)) (i32.eq (local.get $b1) (i32.const 88)))))
                        (then (local.set $b1 (i32.const 0))))))))
      (if (local.get $b1)
        (then
          (call $put (global.get $CBX) (global.get $CBXL))
          (if (i32.ne (local.get $b1) (i32.const 32)) (then (call $put (global.get $CHECKED) (global.get $CHECKEDL))))
          (call $put (global.get $CBX_END) (global.get $CBX_ENDL))
          (call $inline (i32.add (local.get $tptr) (i32.const 4)) (i32.sub (local.get $tlen) (i32.const 4))))
        (else (call $inline (local.get $tptr) (local.get $tlen))))
      (if (i32.gt_u (local.get $j) (i32.add (local.get $i) (i32.const 1)))
        (then (call $putb (i32.const 10))
              (call $render_list_range (i32.add (local.get $i) (i32.const 1)) (local.get $j))
              (global.set $op (i32.sub (global.get $op) (i32.const 1)))))
      (call $put (global.get $LI_C) (global.get $LI_CL))
      (local.set $i (local.get $j)) (br $l)))
    (if (local.get $ord) (then (call $put (global.get $OL_C) (global.get $OL_CL))) (else (call $put (global.get $UL_C) (global.get $UL_CL)))))

  (func $render_list (param $p i32)
    (local $cur i32) (local $k i32) (local $cnt i32) (local $rl i32)
    (local.set $cur (i32.load (i32.add (local.get $p) (i32.const 20))))
    (local.set $cnt (i32.load (i32.add (local.get $p) (i32.const 24))))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $k) (local.get $cnt)))
      (i32.store (i32.add (global.get $JOIN) (i32.mul (local.get $k) (i32.const 4))) (local.get $cur))
      (local.set $rl (i32.load (i32.add (local.get $cur) (i32.const 12))))
      (local.set $cur (i32.add (local.get $cur) (i32.add (local.get $rl) (i32.const 16))))
      (local.set $k (i32.add (local.get $k) (i32.const 1))) (br $l)))
    (call $render_list_range (i32.const 0) (local.get $cnt)))

  ;; ===================== draft / close / swap / feed =====================
  (func $draft (param $p i32)
    (local $o i32)
    (local.set $o (i32.load (local.get $p)))
    (if (i32.eq (local.get $o) (i32.const 112)) (then (call $render_para (local.get $p)) (return)))
    (if (i32.eq (local.get $o) (i32.const 102)) (then (call $render_fence (local.get $p)) (return)))
    (if (i32.eq (local.get $o) (i32.const 113)) (then (call $render_quote (local.get $p)) (return)))
    (if (i32.eq (local.get $o) (i32.const 108)) (then (call $render_list (local.get $p)) (return))))

  (func $close (param $p i32)
    (call $draft (local.get $p))
    (global.set $arena (i32.load (i32.add (local.get $p) (i32.const 20))))
    (i32.store (local.get $p) (i32.const 0))
    (i32.store (i32.add (local.get $p) (i32.const 24)) (i32.const 0))
    (i32.store (i32.add (local.get $p) (i32.const 8)) (i32.const 0)))

  (func $swap (param $p i32) (param $kind i32)
    (call $close (local.get $p))
    (i32.store (local.get $p) (local.get $kind))
    (i32.store (i32.add (local.get $p) (i32.const 20)) (global.get $arena))
    (i32.store (i32.add (local.get $p) (i32.const 24)) (i32.const 0)))

  (func $new_parser (result i32)
    (local $p i32)
    (local.set $p (global.get $state))
    (global.set $state (i32.add (global.get $state) (i32.const 320)))
    (i32.store (local.get $p) (i32.const 0))
    (i32.store (i32.add (local.get $p) (i32.const 8)) (i32.const 0))
    (i32.store (i32.add (local.get $p) (i32.const 24)) (i32.const 0))
    (i32.store (i32.add (local.get $p) (i32.const 16)) (i32.const 0))
    (i32.store (i32.add (local.get $p) (i32.const 20)) (global.get $arena))
    (local.get $p))

  (func $feed (param $p i32) (param $ptr i32) (param $len i32)
    (local $open i32) (local $lvl i32) (local $rpp i32) (local $rll i32)
    (local $fch i32) (local $fcnt i32) (local $ip i32) (local $il i32)
    (local $ind i32) (local $ord i32) (local $stt i32)
    (local.set $open (i32.load (local.get $p)))
    ;; inside fence
    (if (i32.eq (local.get $open) (i32.const 102))
      (then
        (if (call $m_fence_close (local.get $p) (local.get $ptr) (local.get $len))
          (then (call $close (local.get $p)))
          (else (call $rec_simple (local.get $p) (local.get $ptr) (local.get $len))))
        (return)))
    ;; blank line
    (if (call $is_blank (local.get $ptr) (local.get $len)) (then (call $close (local.get $p)) (return)))
    ;; fence open
    (if (call $m_fence_open (local.get $ptr) (local.get $len))
      (then
        (local.set $fch (global.get $r0)) (local.set $fcnt (global.get $r1))
        (local.set $ip (global.get $rp)) (local.set $il (global.get $rl))
        (call $close (local.get $p))
        (i32.store (local.get $p) (i32.const 102))
        (i32.store (i32.add (local.get $p) (i32.const 20)) (global.get $arena))
        (i32.store (i32.add (local.get $p) (i32.const 24)) (i32.const 0))
        (i32.store (i32.add (local.get $p) (i32.const 12)) (local.get $fch))
        (i32.store (i32.add (local.get $p) (i32.const 16)) (local.get $fcnt))
        (memory.copy (i32.add (local.get $p) (i32.const 64)) (local.get $ip) (local.get $il))
        (i32.store (i32.add (local.get $p) (i32.const 4)) (i32.add (local.get $p) (i32.const 64)))
        (i32.store (i32.add (local.get $p) (i32.const 8)) (local.get $il))
        (return)))
    ;; heading
    (if (call $m_heading (local.get $ptr) (local.get $len))
      (then
        (local.set $lvl (global.get $r0)) (local.set $rpp (global.get $rp)) (local.set $rll (global.get $rl))
        (call $close (local.get $p))
        (call $put (global.get $H_O) (global.get $H_OL)) (call $emit_num (local.get $lvl)) (call $put (global.get $H_MID) (global.get $H_MIDL))
        (call $inline (local.get $rpp) (local.get $rll))
        (call $put (global.get $H_C) (global.get $H_CL)) (call $emit_num (local.get $lvl)) (call $put (global.get $H_END) (global.get $H_ENDL))
        (return)))
    ;; hr
    (if (call $m_hr (local.get $ptr) (local.get $len))
      (then (call $close (local.get $p)) (call $put (global.get $HR) (global.get $HRL)) (return)))
    ;; blockquote
    (if (call $m_bq (local.get $ptr) (local.get $len))
      (then
        (local.set $rpp (global.get $rp)) (local.set $rll (global.get $rl))
        (if (i32.ne (local.get $open) (i32.const 113)) (then (call $swap (local.get $p) (i32.const 113))))
        (call $rec_simple (local.get $p) (local.get $rpp) (local.get $rll))
        (return)))
    ;; list
    (if (call $m_list (local.get $ptr) (local.get $len))
      (then
        (local.set $ind (global.get $r0)) (local.set $ord (global.get $r1)) (local.set $stt (global.get $r2))
        (local.set $rpp (global.get $rp)) (local.set $rll (global.get $rl))
        (if (i32.ne (local.get $open) (i32.const 108)) (then (call $swap (local.get $p) (i32.const 108))))
        (call $rec_list (local.get $p) (local.get $ind) (local.get $ord) (local.get $stt) (local.get $rpp) (local.get $rll))
        (return)))
    ;; paragraph
    (if (i32.ne (local.get $open) (i32.const 112)) (then (call $swap (local.get $p) (i32.const 112))))
    (call $trimStart (local.get $ptr) (local.get $len))
    (call $rec_simple (local.get $p) (global.get $rp) (global.get $rl)))

  ;; ===================== exports =====================
  (func (export "input_ptr") (result i32) (global.get $INBUF))

  (func (export "create") (result i32)
    (global.set $op (global.get $STABLE))
    (global.set $arena (global.get $ARENA0))
    (global.set $state (global.get $STATE0))
    (global.set $buflen (i32.const 0))
    (global.set $stc (i32.const 0))
    (call $new_parser))

  (func (export "push") (param $h i32) (param $ptr i32) (param $len i32) (result i64)
    (local $start i32) (local $i i32) (local $c i32) (local $ls i32) (local $rem i32)
    (local.set $start (global.get $op))
    ;; append chunk (strip \r) into BUFREG
    (local.set $i (i32.const 0))
    (block $e (loop $l
      (br_if $e (i32.ge_u (local.get $i) (local.get $len)))
      (local.set $c (i32.load8_u (i32.add (local.get $ptr) (local.get $i))))
      (if (i32.ne (local.get $c) (i32.const 13))
        (then (i32.store8 (i32.add (global.get $BUFREG) (global.get $buflen)) (local.get $c))
              (global.set $buflen (i32.add (global.get $buflen) (i32.const 1)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l)))
    ;; feed complete lines
    (local.set $i (i32.const 0)) (local.set $ls (i32.const 0))
    (block $e2 (loop $l2
      (br_if $e2 (i32.ge_u (local.get $i) (global.get $buflen)))
      (if (i32.eq (i32.load8_u (i32.add (global.get $BUFREG) (local.get $i))) (i32.const 10))
        (then (call $feed (local.get $h) (i32.add (global.get $BUFREG) (local.get $ls)) (i32.sub (local.get $i) (local.get $ls)))
              (local.set $ls (i32.add (local.get $i) (i32.const 1)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1))) (br $l2)))
    ;; compact tail
    (local.set $rem (i32.sub (global.get $buflen) (local.get $ls)))
    (memory.copy (global.get $BUFREG) (i32.add (global.get $BUFREG) (local.get $ls)) (local.get $rem))
    (global.set $buflen (local.get $rem))
    (i64.or (i64.shl (i64.extend_i32_u (local.get $start)) (i64.const 32))
            (i64.extend_i32_u (i32.sub (global.get $op) (local.get $start)))))

  (func (export "peek") (param $h i32) (result i64)
    (local $sop i32) (local $sar i32) (local $sst i32) (local $base i32) (local $reclen i32) (local $outlen i32)
    (local.set $sop (global.get $op)) (local.set $sar (global.get $arena)) (local.set $sst (global.get $state))
    ;; clone parser struct + records
    (memory.copy (global.get $TEMPP) (local.get $h) (i32.const 320))
    (local.set $reclen (i32.sub (global.get $arena) (i32.load (i32.add (local.get $h) (i32.const 20)))))
    (local.set $base (global.get $arena))
    (memory.copy (local.get $base) (i32.load (i32.add (local.get $h) (i32.const 20))) (local.get $reclen))
    (i32.store (i32.add (global.get $TEMPP) (i32.const 20)) (local.get $base))
    (global.set $arena (i32.add (local.get $base) (local.get $reclen)))
    (global.set $op (global.get $SCRATCH))
    (if (i32.gt_u (global.get $buflen) (i32.const 0)) (then (call $feed (global.get $TEMPP) (global.get $BUFREG) (global.get $buflen))))
    (call $draft (global.get $TEMPP))
    (local.set $outlen (i32.sub (global.get $op) (global.get $SCRATCH)))
    (global.set $op (local.get $sop)) (global.set $arena (local.get $sar)) (global.set $state (local.get $sst))
    (i64.or (i64.shl (i64.extend_i32_u (global.get $SCRATCH)) (i64.const 32)) (i64.extend_i32_u (local.get $outlen))))

  (func (export "end") (param $h i32) (result i64)
    (local $start i32)
    (local.set $start (global.get $op))
    (if (i32.gt_u (global.get $buflen) (i32.const 0))
      (then (call $feed (local.get $h) (global.get $BUFREG) (global.get $buflen)) (global.set $buflen (i32.const 0))))
    (call $close (local.get $h))
    (i64.or (i64.shl (i64.extend_i32_u (local.get $start)) (i64.const 32))
            (i64.extend_i32_u (i32.sub (global.get $op) (local.get $start)))))
)
